// ########## Import Header Constants Here ##########
export const LOAD_HEADER = "LOAD_HEADER";
export const LOAD_HEADER_ATTEMPT = "LOAD_HEADER_ATTEMPT";
export const LOAD_HEADER_SUCCESS = "LOAD_HEADER_SUCCESS";
export const LOAD_HEADER_FAIL = "LOAD_HEADER_FAIL";

// ########## Import Categories Constants Here ##########
export const LOAD_CATEGORIES = "LOAD_CATEGORIES";
export const LOAD_CATEGORIES_ATTEMPT = "LOAD_CATEGORIES_ATTEMPT";
export const LOAD_CATEGORIES_SUCCESS = "LOAD_CATEGORIES_SUCCESS";
export const LOAD_CATEGORIES_FAIL = "LOAD_CATEGORIES_FAIL";

// ########## Import Sub Categories Gallery Constants Here ##########
export const LOAD_SUB_CATEGORIES_GALLERY = "LOAD_SUB_CATEGORIES_GALLERY";
export const LOAD_SUB_CATEGORIES_GALLERY_ATTEMPT =
  "LOAD_SUB_CATEGORIES_GALLERY_ATTEMPT";
export const LOAD_SUB_CATEGORIES_GALLERY_SUCCESS =
  "LOAD_SUB_CATEGORIES_GALLERY_SUCCESS";
export const LOAD_SUB_CATEGORIES_GALLERY_FAIL =
  "LOAD_SUB_CATEGORIES_GALLERY_FAIL";

// ########## Import Footer Constants Here ##########
export const LOAD_FOOTER = "LOAD_FOOTER";
export const LOAD_FOOTER_ATTEMPT = "LOAD_FOOTER_ATTEMPT";
export const LOAD_FOOTER_SUCCESS = "LOAD_FOOTER_SUCCESS";
export const LOAD_FOOTER_FAIL = "LOAD_FOOTER_FAIL";

// ########## Import Details Page Constants Here ##########
export const LOAD_DETAILS_PAGE = "LOAD_DETAILS_PAGE";
export const LOAD_DETAILS_PAGE_ATTEMPT = "LOAD_DETAILS_PAGE_ATTEMPT";
export const LOAD_DETAILS_PAGE_SUCCESS = "LOAD_DETAILS_PAGE_SUCCESS";
export const LOAD_DETAILS_PAGE_FAIL = "LOAD_DETAILS_PAGE_FAIL";
