// ########## Import Header Constants Here ##########
export const LOAD_HEADER = "LOAD_HEADER";
export const LOAD_HEADER_ATTEMPT = "LOAD_HEADER_ATTEMPT";
export const LOAD_HEADER_SUCCESS = "LOAD_HEADER_SUCCESS";
export const LOAD_HEADER_FAIL = "LOAD_HEADER_FAIL";

// ########## Import Categories Constants Here ##########
export const LOAD_CATEGORIES = "LOAD_CATEGORIES";
export const LOAD_CATEGORIES_ATTEMPT = "LOAD_CATEGORIES_ATTEMPT";
export const LOAD_CATEGORIES_SUCCESS = "LOAD_CATEGORIES_SUCCESS";
export const LOAD_CATEGORIES_FAIL = "LOAD_CATEGORIES_FAIL";
export const SWITCH_CATEGORIES_ACTIVE = "SWITCH_CATEGORIES_ACTIVE";
export const SWITCH_CATEGORIES_RIGHT = "SWITCH_CATEGORIES_RIGHT";
export const SWITCH_CATEGORIES_LEFT = "SWITCH_CATEGORIES_LEFT";

// ########## Import Sub Categories Gallery Constants Here ##########
export const LOAD_SUB_CATEGORIES_GALLERY = "LOAD_SUB_CATEGORIES_GALLERY";
export const LOAD_SUB_CATEGORIES_GALLERY_ATTEMPT =
  "LOAD_SUB_CATEGORIES_GALLERY_ATTEMPT";
export const LOAD_SUB_CATEGORIES_GALLERY_SUCCESS =
  "LOAD_SUB_CATEGORIES_GALLERY_SUCCESS";
export const LOAD_SUB_CATEGORIES_GALLERY_FAIL =
  "LOAD_SUB_CATEGORIES_GALLERY_FAIL";

// ########## Import Footer Constants Here ##########
export const LOAD_FOOTER = "LOAD_FOOTER";
export const LOAD_FOOTER_ATTEMPT = "LOAD_FOOTER_ATTEMPT";
export const LOAD_FOOTER_SUCCESS = "LOAD_FOOTER_SUCCESS";
export const LOAD_FOOTER_FAIL = "LOAD_FOOTER_FAIL";

// ############# Delivery Data ###############

export const GET_DELIVERY_DATA = "GET_DELIVERY_DATA";
export const GET_DELIVERY_DATA_ATTEMPT = "GET_DELIVERY_DATA_ATTEMPT";
export const GET_DELIVERY_DATA_SUCCESS = "GET_DELIVERY_DATA_SUCCESS";
export const GET_DELIVERY_DATA_FAIL = "GET_DELIVERY_DATA_FAIL";
