// ########## Import Categories Constants Here ##########
export const LOAD_CATEGORIES = "LOAD_CATEGORIES";
export const LOAD_CATEGORIES_ATTEMPT = "LOAD_CATEGORIES_ATTEMPT";
export const LOAD_CATEGORIES_SUCCESS = "LOAD_CATEGORIES_SUCCESS";
export const LOAD_CATEGORIES_FAIL = "LOAD_CATEGORIES_FAIL";
export const SWITCH_CATEGORIES_ACTIVE = "SWITCH_CATEGORIES_ACTIVE";
export const SWITCH_CATEGORIES_RIGHT = "SWITCH_CATEGORIES_RIGHT";
export const SWITCH_CATEGORIES_LEFT = "SWITCH_CATEGORIES_LEFT";

// ########## Import Sub Categories Gallery Constants Here ##########
export const LOAD_SUB_CATEGORIES_GALLERY = "LOAD_SUB_CATEGORIES_GALLERY";
export const LOAD_SUB_CATEGORIES_GALLERY_ATTEMPT =
  "LOAD_SUB_CATEGORIES_GALLERY_ATTEMPT";
export const LOAD_SUB_CATEGORIES_GALLERY_SUCCESS =
  "LOAD_SUB_CATEGORIES_GALLERY_SUCCESS";
export const LOAD_SUB_CATEGORIES_GALLERY_FAIL =
  "LOAD_SUB_CATEGORIES_GALLERY_FAIL";
  